let a = "My name is Cynthia Nakurel";
console.log(a.split());
console.log(a.replace("name", "identity"));
console.log(a.length);
console.log(a.charAt(0));
console.log(a.split(" ").reverse().join());
console.log(a);
console.log(a.at(12));
console.log(a.at(-1));
console.log(a.charCodeAt(0));
console.log(a[0]);